openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
paths:
  /greeting/{name}:
    get:
      summary: Get a greeting
      operationId: get-greeting
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
          description: Name to greet
          examples:
          - world
          maxLength: 30
        example: world
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GreetingOutputBody"
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
components:
  schemas:
    ErrorDetail:
      type: object
      additionalProperties: false
      properties:
        location:
          type: string
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
        message:
          type: string
          description: Error message text
        value:
          description: The value at the given location
    ErrorModel:
      type: object
      additionalProperties: false
      properties:
        $schema:
          type: string
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
          - Property foo is required but is missing.
        errors:
          type: array
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem.
          format: uri
          examples:
          - https://example.com/error-log/abc123
        status:
          type: integer
          description: HTTP status code
          format: int64
          examples:
          - 400
        title:
          type: string
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
          - Bad Request
        type:
          type: string
          description: A URI reference to human-readable documentation for the error.
          format: uri
          default: about:blank
          examples:
          - https://example.com/errors/example
    GreetingOutputBody:
      type: object
      additionalProperties: false
      properties:
        $schema:
          type: string
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
        message:
          type: string
          description: Greeting message
          examples:
          - Hello, world!
      required:
      - message
